development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://ramfayeserver.herokuapp.com/faye" # since I couldn't get aws port(9292) open to public access I have used this.
  secret_token: "batkaro"
  signature_expiration: 3600 # one hour
